# Generated by Django 4.1.3 on 2023-01-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
